# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"i\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05\x12\x11\n\timage_url\x18\x06 \x01(\t\x12\r\n\x05stock\x18\x07 \x01(\x05\"\x14\n\x12ProductListRequest\"9\n\x13ProductListResponse\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.product.Product\"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"4\n\x0fProductResponse\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\"j\n\x14ProductCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05\x12\x11\n\timage_url\x18\x04 \x01(\t\x12\r\n\x05stock\x18\x05 \x01(\x05\":\n\x15ProductCreateResponse\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\"v\n\x14ProductUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05\x12\x11\n\timage_url\x18\x05 \x01(\t\x12\r\n\x05stock\x18\x06 \x01(\x05\":\n\x15ProductUpdateResponse\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\"\"\n\x14ProductDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"(\n\x15ProductDeleteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe8\x02\n\x0eProductService\x12\x41\n\x04List\x12\x1b.product.ProductListRequest\x1a\x1c.product.ProductListResponse\x12\x38\n\x03Get\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponse\x12G\n\x06\x43reate\x12\x1d.product.ProductCreateRequest\x1a\x1e.product.ProductCreateResponse\x12G\n\x06Update\x12\x1d.product.ProductUpdateRequest\x1a\x1e.product.ProductUpdateResponse\x12G\n\x06\x44\x65lete\x12\x1d.product.ProductDeleteRequest\x1a\x1e.product.ProductDeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCT']._serialized_start=26
  _globals['_PRODUCT']._serialized_end=131
  _globals['_PRODUCTLISTREQUEST']._serialized_start=133
  _globals['_PRODUCTLISTREQUEST']._serialized_end=153
  _globals['_PRODUCTLISTRESPONSE']._serialized_start=155
  _globals['_PRODUCTLISTRESPONSE']._serialized_end=212
  _globals['_PRODUCTREQUEST']._serialized_start=214
  _globals['_PRODUCTREQUEST']._serialized_end=242
  _globals['_PRODUCTRESPONSE']._serialized_start=244
  _globals['_PRODUCTRESPONSE']._serialized_end=296
  _globals['_PRODUCTCREATEREQUEST']._serialized_start=298
  _globals['_PRODUCTCREATEREQUEST']._serialized_end=404
  _globals['_PRODUCTCREATERESPONSE']._serialized_start=406
  _globals['_PRODUCTCREATERESPONSE']._serialized_end=464
  _globals['_PRODUCTUPDATEREQUEST']._serialized_start=466
  _globals['_PRODUCTUPDATEREQUEST']._serialized_end=584
  _globals['_PRODUCTUPDATERESPONSE']._serialized_start=586
  _globals['_PRODUCTUPDATERESPONSE']._serialized_end=644
  _globals['_PRODUCTDELETEREQUEST']._serialized_start=646
  _globals['_PRODUCTDELETEREQUEST']._serialized_end=680
  _globals['_PRODUCTDELETERESPONSE']._serialized_start=682
  _globals['_PRODUCTDELETERESPONSE']._serialized_end=722
  _globals['_PRODUCTSERVICE']._serialized_start=725
  _globals['_PRODUCTSERVICE']._serialized_end=1085
# @@protoc_insertion_point(module_scope)
